name: Rust

on:
  pull_request:
    branches: [master, main]
  merge_group:
  push:
    branches: ["master"]

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.rs
            Cargo.lock
      - name: Install latest nightly
        if: env.GIT_DIFF
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: false
      - name: Install wasm32 toolchain
        if: env.GIT_DIFF
        run: rustup target add wasm32-unknown-unknown
      - name: Install near cli and cargo near
        if: env.GIT_DIFF
        run: npm i
      - name: Build
        if: env.GIT_DIFF
        run: npm run cook
      - name: Clippy
        if: env.GIT_DIFF
        run: npm run lint
      - name: Run tests
        if: env.GIT_DIFF
        run: npm run test
